### ISSUE TITLE
Weather data Platform/Integration is broken

### ISSUE THREAD

**Issue by Pirol62** [Danielhiversen/home_assistant_weather_data#15]
The connect creates an error since 2 days:

````
Logger: custom_components.weather_data.sensor
Source: custom_components/weather_data/sensor.py:181
Integration: weather_data (documentation, issues)
First occurred: 12:37:33 (11 occurrences)
Last logged: 12:37:34

Retrying in 15 minutes: https://api.met.no/weatherapi/locationforecast/1.9/?lat=51.26851674247047&lon=6.6165136211750095&msl=45 returned 404
Retrying in 19 minutes: https://api.met.no/weatherapi/locationforecast/1.9/?lat=51.26851674247047&lon=6.6165136211750095&msl=45 returned 404
Retrying in 18 minutes: https://api.met.no/weatherapi/locationforecast/1.9/?lat=51.26851674247047&lon=6.6165136211750095&msl=45 returned 404
Retrying in 16 minutes: https://api.met.no/weatherapi/locationforecast/1.9/?lat=51.26851674247047&lon=6.6165136211750095&msl=45 returned 404
Retrying in 20 minutes: https://api.met.no/weatherapi/locationforecast/1.9/?lat=51.26851674247047&lon=6.6165136211750095&msl=45 returned 404
````
Hassio 2021.1.3

**Comment by ripburger** [comment]
I am getting the same errors

**Comment by Danielhiversen** [comment]
Try to update to latest version from master branch

**Comment by Pirol62** [comment]
Now, I have this error:
````
Logger: homeassistant.components.sensor
Source: custom_components/weather_data/sensor.py:99
Integration: Sensor (documentation, issues)
First occurred: 17:32:32 (11 occurrences)
Last logged: 17:32:32

Error while setting up weather_data platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/weather_data/sensor.py", line 99, in async_setup_platform
    "altitude": str(int(float(urlparams.get("altitude", elevation)))),
NameError: name 'urlparams' is not defined
````

**Comment by Pirol62** [comment]
@Danielhiversen 
Ok, installed the 0.2.1 and the integration works again. Thanks

Unfortunately, the symbol provides the weather text and not the code anymore so that all my symbos transformation for the custom button card does not work.
Do you have a table with the correct weather text information or can you provide the code again?
