### ISSUE TITLE
No longer works since 2021.11.5

### ISSUE THREAD

**Issue by Nessy1970** [Danielhiversen/home_assistant_weather_data#30]
The component no longer loads since version 2021.12.0

Works under 2021.11.5

Log details (ERROR) :
Logger: homeassistant.components.sensor
Source: helpers/entity.py:541
Integration: Capteur (documentation, issues)
First occurred: 12:38:45 (2 occurrences)
Last logged: 12:38:45

Error adding entities for domain sensor with platform weather_data
Error while setting up weather_data platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
TypeError: <lambda>() takes 0 positional arguments but 1 was given

**Comment by Pirol62** [comment]
The modification wasn't a good idea. Doesn't work anymore

**Comment by mabahj** [comment]
Getting same error on 2022.3.3. The weather.home sensor is in place and working, but not for example dewpointTemperature, which earlier had a sensor.weather_dewpoint_temperature sensor.
```
2022-03-08 20:34:50 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform weather_data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 593, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
TypeError: <lambda>() takes 0 positional arguments but 1 was given
2022-03-08 20:34:50 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up weather_data platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 593, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```
